ASPNET/Models/EventsViewModel.cs
using Database.Models;

namespace ASPNET.Models
{
    public class EventsViewModel
    {
        public IEnumerable<Event> Events { get; set; }
        public List<Database.Models.Genre> EventTypes { get; set; }
    }
}

ASPNET/Controllers/EventsController.cs
using ASPNET.Models;
using Database;
using Database.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using ASPNET.Helpers;
using Microsoft.AspNetCore.Identity;

namespace ASPNET.Controllers
{
    public class EventsController : Controller
    {
        private readonly EventsDbContext context;
        private readonly UserManager<User> userManager;

        public EventsController(EventsDbContext context, UserManager<User> userManager)
        {
            this.context = context;
            this.userManager = userManager;

            //if (context.Users. == 0)
            //{
            //User u = new User()
            //{
            //Name = "Admin",
            //Email = "Admin@gmail.com",
            ///Password = "1234"
            //};
            //context.Users.Add(u);
            //context.SaveChanges();
            //}
        }

        public async Task<IActionResult> Index()
        {
            var events = context.Events.Include(x => x.Images).Include(e=>e.Owner).Include(e=>e.Place).ToList();

            EventsViewModel eventsViewModel = new EventsViewModel();
            eventsViewModel.Events = events;
            eventsViewModel.EventTypes = context.Genres.ToList();

            if (HttpContext.User.Identity == null) return BadRequest();
            var user = context.Users.Where(u => u.UserName == HttpContext.User.Identity.Name).Include(u => u.FavoriteEvents).First();//await userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            ViewData["test"] = new SelectList(user.FavoriteEvents, nameof(Event.Id), nameof(Event.Id))
                                             .ToList()
                                             .Select(x => int.Parse(x.Value)).ToList();

            //ViewBag.FavoriteEvents = new SelectList(user.FavoriteEvents, nameof(Event.Id), nameof(Event.Id));
            return View(eventsViewModel);
        }

        public IActionResult Details(int id)
        {
            if (id <= 0) return BadRequest();

            var _event = context.Events.Where(x => x.Id == id).Include(x => x.Images).First();

            if (_event == null) return NotFound();

            return View(_event);
        }

        public IActionResult Manage()
        {
            var events = context.Events.Include(e => e.Place).Include(e => e.Owner).ToList();

            return View(events);
        }

        public IActionResult Create()
        {
            var places = new SelectList(context.Places, nameof(Place.Id), nameof(Place.Name));
            ViewBag.PlaceTypeList = places;



            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Event ev)
        {
            if (HttpContext.User.Identity == null) return BadRequest();
            var user = await userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            
            ev.Owner = user;
            user.CreatedEvents.Add(ev);

            Image img1 = new Image()
            {
                Path = @"https://images.wallpaperscraft.ru/image/single/most_zdaniia_ogni_384679_1600x1200.jpg",
                Title = "First Image"
            };

            Image img2 = new Image()
            {
                Path = @"https://images.wallpaperscraft.ru/image/single/tserkov_ostrov_more_384743_1600x1200.jpg",
                Title = "Second Image"
            };

            Image img3 = new Image()
            {
                Path = @"https://images.wallpaperscraft.ru/image/single/gora_oblaka_les_384664_1600x1200.jpg",
                Title = "Third Image"
            };

            ev.Images.Add(img1);
            ev.Images.Add(img2);
            ev.Images.Add(img3);

            img1.Event = ev;
            img2.Event = ev;
            img3.Event = ev;

            context.Images.Add(img1);
            context.Images.Add(img2);
            context.Images.Add(img3);


            context.Events.Add(ev);
            context.SaveChanges();

            TempData[WebConstants.TOASTR_MESSAGE] = new Toster()
            {
                Text = "Event was created successully!",
                Action = Models.Action.Create
            };

            var events = context.Events.Include(e => e.Place).Include(e => e.Owner).ToList();

            return View(nameof(Manage), events);


        }

        public IActionResult Edit(int id)
        {
            var ev = context.Events.Find(id);
            ViewBag.PlaceTypeList = new SelectList(context.Places, nameof(Place.Id), nameof(Place.Name));


            return View(nameof(Create), ev);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Event ev)
        {
            if (HttpContext.User.Identity == null) return BadRequest();
            var user = await userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            ev.Owner = user;
            user.CreatedEvents.Add(ev);

            context.Events.Update(ev);
            context.SaveChanges();


            TempData[WebConstants.TOASTR_MESSAGE] = new Toster()
            {
                Text = "Event was changed successully!",
                Action = Models.Action.Update
            };

            var events = context.Events.Include(e => e.Place).Include(e => e.Owner).ToList();

            return View(nameof(Manage), events);
        }

        public IActionResult Delete(int id)
        {
            if (id < 0) return BadRequest();

            var _event = context.Events.Where(x => x.Id == id).Include(x => x.Images).First();

            if (_event == null) return NotFound();

            context.Events.Remove(_event);
            context.SaveChanges();

            TempData[WebConstants.TOASTR_MESSAGE] = new Toster()
            {
                Text = "Event was deleteed successully!",
                Action = Models.Action.Delete
            };

            var events = context.Events.Include(e => e.Place).Include(e => e.Owner).ToList();

            return View(nameof(Manage), events);
        }
    }
}

ASPNET/Controllers/FavoriteEventsController.cs
using Database;
using Microsoft.AspNetCore.Mvc;
using ASPNET.Helpers;
using Database.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace ASPNET.Controllers
{
    public class FavoriteEventsController:Controller
    {
        private readonly EventsDbContext context;
        private readonly UserManager<User> userManager;

        public FavoriteEventsController(EventsDbContext context, UserManager<User> userManager,
                                        SignInManager<User> signInManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            if (HttpContext.User.Identity == null) return BadRequest();

            var user = context.Users.Where(u => u.UserName == HttpContext.User.Identity.Name).Include(u => u.FavoriteEvents).First();

            return View(user.FavoriteEvents);
        }
        public async Task<IActionResult> AddEvent(int id)
        {
            if (id < 0) return BadRequest();

            var ev = context.Events.Where(e => e.Id == id).FirstOrDefault();

            if (ev == null) return NotFound();

            //AddId(id);
            if (HttpContext.User.Identity == null) return BadRequest();

            var user = await userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            user.FavoriteEvents.Add(ev);
            ev.FavoriteUsers.Add(user);
            context.SaveChanges();

            return RedirectToAction("Index", "Events");
        }

        private void AddId(int id)
        {
            var events = HttpContext.Session.Get<List<int>>(WebConstants.FAVORITE_EVENTS_LIST);
            if (events == null) events = new List<int>();

            events.Add(id);

            HttpContext.Session.Set(WebConstants.FAVORITE_EVENTS_LIST, events);
        }


        public async Task<IActionResult> RemoveEvent(int id)
        {
            if (id < 0) return BadRequest();

            var ev = context.Events.Where(e => e.Id == id).Include(e => e.FavoriteUsers).First();

            if (ev == null) return NotFound();

            if (HttpContext.User.Identity == null) return BadRequest();

            var user = context.Users.Where(u => u.UserName == HttpContext.User.Identity.Name).Include(u => u.FavoriteEvents).First();

            user.FavoriteEvents.Remove(ev);
            ev.FavoriteUsers.Remove(user);
            context.SaveChanges();

            return RedirectToAction("Index", "Events", new { id = id });
        }
        private void RemoveId(int id)
        {
            var events = HttpContext.Session.Get<List<int>>(WebConstants.FAVORITE_EVENTS_LIST);

            if (events == null) return;

            events.Remove(id);

            HttpContext.Session.Set(WebConstants.FAVORITE_EVENTS_LIST, events);
        }

        private List<Event> GetEvents()
        {
            var events = HttpContext.Session.Get<List<int>>(WebConstants.FAVORITE_EVENTS_LIST);
            if (events == null) return new List<Event>();

            var eventsOrigin = events.Select(id => context.Events.Find(id)).ToList();

            if (eventsOrigin == null) return new List<Event>();

            return eventsOrigin;
        }
    }
}

ASPNET/Views/Events/Create.cshtml
@using Database.Models
@model Event;
<h1 class="text-center mb-2">Create New Event</h1>

<form asp-action="Create" method="post" class="row g-3">
    @Html.HiddenFor(model => model.Types)
    <div class="mb-3">
        <label asp-for="Title" class="form-label">Title <span class="text-danger">*</span></label>
        <input type="text" asp-for="Title" class="form-control">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Text" class="form-label">Text <span class="text-danger">*</span></label>
        <textarea asp-for="Text" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="IsOnline" class="form-label">Is Online?
            <input type="checkbox" asp-for="IsOnline" class="form-control" id="isOnlineCheckBox">
        </label>
        
        <span asp-validation-for="IsOnline" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Site" class="form-label">Site</label>
        <input type="url" asp-for="Site" class="form-control">
        <span asp-validation-for="Site" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Facebook" class="form-label">Facebook</label>
        <input type="url" asp-for="Facebook" class="form-control">
        <span asp-validation-for="Facebook" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Instagram" class="form-label">Instagram</label>
        <input type="url" asp-for="Instagram" class="form-control">
        <span asp-validation-for="Instagram" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="EventTime" class="form-label">Event Time <span class="text-danger">*</span></label>
        <input type="date" asp-for="EventTime" class="form-control">
        <span asp-validation-for="EventTime" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Price" class="form-label">Price <span class="text-danger">*</span></label>
        <input type="number" min="0" step="10" asp-for="Price" class="form-control">
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="PlaceId" class="form-label">Places</label>
        <select asp-for="PlaceId" asp-items="@ViewBag.PlaceTypeList" class="form-select"></select>
        <span asp-validation-for="PlaceId" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <button asp-action="Manage" class="btn btn-secondary">Back</button>
        @if (Model!=null)
        {
            <button type="submit" asp-action="Edit" class="btn btn-warning">Save</button>
            @Html.HiddenFor(model => model.Id)
        }
        @if (Model == null)
        {
            <button type="submit" class="btn btn-primary">Create</button>
        }
    </div>
</form>

ASPNET/Views/Events/Details.cshtml
@using ASPNET.Helpers
@using Database.Models
@model Event;
@{
    List<int> favoriteIds = Context.Session.Get<List<int>>(WebConstants.FAVORITE_EVENTS_LIST);
    if (favoriteIds == null) favoriteIds = new List<int>();
}

<secion class="text-center">
    <h1>@Model.Title</h1>
</secion>

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
      @for(int i=0;i<Model.Images.Count;i++)
        {
            if (i == 0)
            {
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="@i" class="active" aria-current="true" aria-label="Image @i"></button>
            }
            else
            {
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="@i" aria-current="true" aria-label="Image @i"></button>
            }
        }
  </div>
  <div class="carousel-inner">
      @for(int i=0;i<Model.Images.Count;i++)
        {
            if(i==0)
            {
                <div class="carousel-item active">
                    <img src="@Model.Images.ElementAt(i).Path" class="d-block w-100" alt="@Model.Images.ElementAt(i).Title">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>@Model.Images.ElementAt(i).Title</h5>
                    </div>
                </div>
            }
            else
            {
                <div class="carousel-item">
                    <img src="@Model.Images.ElementAt(i).Path" class="d-block w-100" alt="@Model.Images.ElementAt(i).Title">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>@Model.Images.ElementAt(i).Title</h5>
                    </div>
                </div>
            }
        }
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div>
    <p>@Model.Text</p>
    <p>Price @Model.Price$</p>
</div>
<div>
    @if (favoriteIds.Contains(Model.Id))
    {
        <a asp-controller="FavoriteEvents" asp-action="RemoveEvent" asp-route-id="@Model.Id" class="mb-1 btn btn-secondary">Remove From Favorites</a>
    }
    else{
        <a asp-controller="FavoriteEvents" asp-action="AddEvent" asp-route-id="@Model.Id" class="mb-1 btn btn-primary">Add To Favorites</a>
    }
</div>
<div class="sticz">
    @foreach(var type in Model.Types)
    {
        <button class="btn btn-outline-secondary">@type.Name</button>
    }
</div>

<script>
    var myCarousel = document.querySelector('#myCarousel')
    var carousel = new bootstrap.Carousel(myCarousel, {
        interval: 2000,
        wrap: false
    })
</script>

ASPNET/Views/Events/Index.cshtml
@using ASPNET.Helpers
@model EventsViewModel;
@{
    List<int> favoriteIds = ViewData["test"] as List<int>;
    if (favoriteIds == null) favoriteIds = new List<int>();
}
<div>
    <h1 class="text-center my-4">New Events</h1>
    <div class="my-3">
        <h2>Types</h2>
        <div>
            @foreach(var type in Model.EventTypes)
            {
                <button class="btn btn-outline-secondary">@type.Name</button>
            }
        </div>
    </div>
    <div class="row">
        
        @foreach(var _event in Model.Events)
        {
            <div class="col">
                <div style="width: 18rem;">
                    <img src="@_event.Images.First()?.Path" class="card-img-top" alt="@_event.Images.First()?.Title">
                    <div class="cb-pink my-flex">
                        <h5 class="w-auto text-center">@_event.Title</h5>
                        <p class="w-auto">@_event.EventTime</p>
                        <p class="w-auto">@_event.Place?.Route</p>
                        <a asp-action="Details" asp-route-id="@_event.Id" class="btn btn-primary w-auto mb-1" aria-current="true">Details</a>
                        
                        @if (favoriteIds.Contains(_event.Id))
                        {
                            <a asp-controller="FavoriteEvents" asp-action="RemoveEvent" asp-route-id="@_event.Id" class="mb-1">
                                <img src="/images/favorite_heart.png" class="f-heart">
                            </a>
                        }
                        else
                        {
                            <a asp-controller="FavoriteEvents" asp-action="AddEvent" asp-route-id="@_event.Id" class="mb-1">
                                <img src="/images/favorite_heart.png" class="c-heart">
                            </a>
                        }
                        
                    </div>

                </div>
            </div>
        }
    </div>
</div>
<style>
    .my-flex{
    display: flex;
    flex-direction: column;
    align-items: center;
}
.f-heart,
.c-heart{
    width: auto;
    height: 20px;
    transition: 0.5s;
}
.f-heart:hover{
    filter:grayscale(1);
}
.c-heart{
    filter:grayscale(1);
}
.c-heart:hover{
    filter:grayscale(0);
}
</style>

ASPNET/Views/Events/Manage.cshtml
@using ASPNET.Helpers
@using Database.Models
@model IEnumerable<Event>;
@{
    Toster? toastrMsg = TempData[WebConstants.TOASTR_MESSAGE] as Toster;
}

<h1 class="text-center">Events List</h1>

<div class="overflow-scroll">
<table class="table mt-4">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Is Online</th>
            <th scope="col">Place</th>
            <th scope="col">Site</th>
            <th scope="col">Facebook</th>
            <th scope="col">Instagram</th>
            <th scope="col">Creation Time</th>
            <th scope="col">Event Time</th>
            <th scope="col">Price</th>
            <th scope="col">Owner</th>
            <th scope="col">Is Moderated</th>
            <th scope="col">Event Types</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var _event in Model)
        {
            <tr>
                <th class="align-middle" scope="row">@_event.Id</th>
                <td class="align-middle">@_event.Title</td>
                <td class="align-middle">@_event.IsOnline</td>
                <td class="align-middle">@_event.Place?.Name</td>
                <td class="align-middle">@_event.Site</td>
                <td class="align-middle text-truncate">@_event.Facebook</td>
                <td class="align-middle text-truncate">@_event.Instagram</td>
                <td class="align-middle">@_event.CreationTime</td>
                <td class="align-middle">@_event.EventTime</td>
                <td class="align-middle">@_event.Price</td>
                <td class="align-middle">@_event.Owner?.UserName</td>
                <td class="align-middle">@_event.IsModerated</td>
                 <td class="align-middle">
                    @foreach(var type in @_event.Types)
                    {
                        <p>@type.Name</p>
                    }
                 </td>
                <td class="align-middle">
                    <div class="btn-group" role="group">
                        <a asp-action="Edit" asp-route-id="@_event.Id" class="btn btn-warning">Edit</a>
                        <a asp-action="Delete" asp-route-id="@_event.Id" class="btn btn-danger">Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

<a asp-action="Create" class="btn btn-primary">Create New Event</a>
<div class="position-fixed top-0 end-0 p-3" style="z-index: 11">
    <div id="toastr-block" data-bs-autohide="true" data-bs-animation="true" class="toast align-items-center text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                @toastrMsg?.Text
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

@if (toastrMsg != null)
{
    @section Scripts
    {
    <script>
        var toastLiveExample = document.getElementById('toastr-block');
        var toast = new bootstrap.Toast(toastLiveExample);
        toast.show();
    </script>
    }
}